### ISSUE TITLE
老哥，什么时候更新一波Monterey

### ISSUE THREAD

**Issue by Myperfectworld0** [ycg31/Hackintosh#7]
Monterey出了，现在这个EFI好像不兼容

**Comment by qwer130140190** [comment]
是啊，顺便加个5800x的config.plist

**Comment by ycg31** [comment]
最近忙的，没时间折腾，等过段时间，Monterey稳定了再折腾

**Comment by ycg31** [comment]
已更新到12.0.1
5800x是直接免驱的。性能文件没啥意思.
